import fs from 'fs';
import path from 'path';
import { getTenantId } from './tenantContext.js';

export interface ForwardingRule { id:string; name:string; accountId?:string; sourceId:string; sourceTitle:string; sourceUsername?:string; targetIds:string[]; targetTitles:string[]; removeForwardSignature:boolean; duplicateProtection:boolean; preserveFormatting?:boolean; useKeywordFilter?:boolean; includeKeywords?:string[]; excludeKeywords?:string[]; filterKeywords?:string[]; mediaFilter?:{allowText:boolean;allowPhoto:boolean;allowVideo:boolean;allowAudio:boolean;allowVoice:boolean;allowDocument:boolean;allowSticker:boolean;allowAnimation:boolean}; senderFilter?:{enabled:boolean;mode:'whitelist'|'blacklist';senderIds:string[];ignoreBots:boolean}; dropLinks?:boolean; prependText?:string; appendText?:string; enabled:boolean; createdAt:number; }
export interface RateLimitConfig { minDelayMs:number; maxMessagesPerMinute:number; autoSleepOnFloodWait:boolean; retryAttempts:number; exponentialBackoff:boolean; }
export interface ForwarderConfig { apiId?:number|string; apiHash?:string; sessionString?:string; botToken?:string; isEngineRunning:boolean; rules:ForwardingRule[]; accounts?:any[]; globalRateLimit?:RateLimitConfig; defaultRemoveSignature:boolean; retryOnFloodWait:boolean; maxRetryCount:number; }
export interface ActivityLog { id:string; timestamp:number; level:'info'|'warn'|'error'|'success'; category:'auth'|'forward'|'duplicate'|'filter'|'system'|'discovery'; title:string; message:string; sourceId?:string; sourceTitle?:string; targetId?:string; targetTitle?:string; accountId?:string; details?:Record<string,any>; messageSnippet?:string; }
export interface EngineStats { totalReceived:number; totalForwarded:number; totalFailed:number; duplicatesBlocked:number; filtersTriggered:number; mediaBlocked?:number; sendersBlocked?:number; floodWaitsHandled?:number; activeRulesCount:number; uptimeSeconds:number; lastActiveTime:number|null; startTime:number|null; }
export interface MessageMappingRecord { id:string; sourceChatId:string; sourceMsgId:number|string; targetChatId:string; targetMsgId:number|string; hash?:string; timestamp:number; }
export const normalizeChatId=(id:string|number):string=>id? id.toString().trim().replace(/^-100/,'').replace(/^-/,'') : '';

const BASE_DATA_DIR=process.env.TG_DATA_DIR||(process.env.VERCEL?'/tmp/tgforwarder-data':path.join(process.cwd(),'.data'));
const tenantDir=()=>path.join(BASE_DATA_DIR,'tenants',getTenantId());
const buildInitialRules=():ForwardingRule[]=>{const s=process.env.TG_SOURCE_ID?.trim(),t=process.env.TG_TARGET_ID?.trim();if(s&&t)return[{id:'rule-env-primary',name:'Auto Funnel (Environment Config)',sourceId:s,sourceTitle:`Source Channel (${s})`,targetIds:[t],targetTitles:[`Target Channel (${t})`],removeForwardSignature:true,duplicateProtection:true,preserveFormatting:true,useKeywordFilter:false,includeKeywords:[],excludeKeywords:[],filterKeywords:[],dropLinks:false,prependText:'',appendText:'',enabled:true,createdAt:Date.now()}];return[];};
const defaultRate:RateLimitConfig={minDelayMs:1200,maxMessagesPerMinute:25,autoSleepOnFloodWait:true,retryAttempts:3,exponentialBackoff:true};

export class StorageManager{
 private static instances=new Map<string,StorageManager>();
 private config:ForwarderConfig; private mappings=new Map<string,MessageMappingRecord>(); private mappingsSaveTimer:NodeJS.Timeout|null=null; private mappingsDirty=false; private static readonly MAPPINGS_FLUSH_INTERVAL_MS=3000; private readonly dataDir:string; private readonly configFile:string; private readonly mappingsFile:string;
 private constructor(){this.dataDir=tenantDir();this.configFile=path.join(this.dataDir,'config.json');this.mappingsFile=path.join(this.dataDir,'mappings.json');this.ensureDataDir();this.config=this.loadConfig();this.loadMappings();}
 public static getInstance(){const id=getTenantId();let item=this.instances.get(id);if(!item){item=new StorageManager();this.instances.set(id,item);}return item;}
 private ensureDataDir(){if(!fs.existsSync(this.dataDir))fs.mkdirSync(this.dataDir,{recursive:true});}
 private loadConfig():ForwarderConfig{const defaults:ForwarderConfig={apiId:'',apiHash:'',sessionString:'',botToken:'',isEngineRunning:false,defaultRemoveSignature:true,retryOnFloodWait:true,maxRetryCount:3,globalRateLimit:{...defaultRate},rules:[]};try{if(fs.existsSync(this.configFile)){const p=JSON.parse(fs.readFileSync(this.configFile,'utf8'));if(Array.isArray(p.rules))p.rules=p.rules.filter((r:ForwardingRule)=>r.sourceId&&r.sourceId.trim());return{...defaults,...p};}}catch(err){console.error('[StorageManager] Error loading config:',err);}return defaults;}
 private loadMappings(){try{if(!fs.existsSync(this.mappingsFile))return;const list:MessageMappingRecord[]=JSON.parse(fs.readFileSync(this.mappingsFile,'utf8'));const cutoff=Date.now()-14*24*60*60*1000;for(const item of list){if(item.timestamp>cutoff){const s=normalizeChatId(item.sourceChatId),t=normalizeChatId(item.targetChatId),key=`${s}_${item.sourceMsgId}_${t}`;this.mappings.set(key,item);if(item.hash)this.mappings.set(`${s}_hash_${item.hash}_${t}`,item);}}}catch(err){console.error('[StorageManager] Error loading mappings:',err);}}
 private scheduleMappingsSave(){this.mappingsDirty=true;if(this.mappingsSaveTimer)return;this.mappingsSaveTimer=setTimeout(()=>{this.mappingsSaveTimer=null;this.flushMappings();},StorageManager.MAPPINGS_FLUSH_INTERVAL_MS);if(typeof this.mappingsSaveTimer.unref==='function')this.mappingsSaveTimer.unref();}
 private flushMappings(){if(!this.mappingsDirty)return;this.mappingsDirty=false;try{this.ensureDataDir();const unique=new Map<string,MessageMappingRecord>();for(const[k,v]of this.mappings)if(!k.includes('_hash_'))unique.set(v.id||k,v);const tmp=`${this.mappingsFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(Array.from(unique.values()).slice(-10000),null,2),'utf8');fs.renameSync(tmp,this.mappingsFile);}catch(err){console.error('[StorageManager] Error writing mappings:',err);}}
 public flushPendingWrites(){if(this.mappingsSaveTimer){clearTimeout(this.mappingsSaveTimer);this.mappingsSaveTimer=null;}this.flushMappings();}
 public isDuplicate(s:string,m:number|string,t:string,h?:string){const a=normalizeChatId(s),b=normalizeChatId(t);return this.mappings.has(`${a}_${m}_${b}`)||(!!h&&this.mappings.has(`${a}_hash_${h}_${b}`));}
 public recordMapping(s:string,m:number|string,t:string,tm:number|string,h?:string){const a=normalizeChatId(s),b=normalizeChatId(t),key=`${a}_${m}_${b}`,record={id:`map-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,sourceChatId:String(s),sourceMsgId:m,targetChatId:String(t),targetMsgId:tm,hash:h,timestamp:Date.now()};this.mappings.set(key,record);if(h)this.mappings.set(`${a}_hash_${h}_${b}`,record);this.scheduleMappingsSave();return record;}
 public getMapping(s:string,m:number|string,t:string){return this.mappings.get(`${normalizeChatId(s)}_${m}_${normalizeChatId(t)}`)||null;}
 public getMappedTargetMsgId(s:string,m:number|string,t:string){const r=this.getMapping(s,m,t);return r?r.targetMsgId:null;}
 public getAllMappingsForSource(s:string,m:number|string){const p=`${normalizeChatId(s)}_${m}_`,out:MessageMappingRecord[]=[];for(const[k,v]of this.mappings)if(k.startsWith(p)&&!k.includes('_hash_'))out.push(v);return out;}
 public getAllMappings(limit=100){const u=new Map<string,MessageMappingRecord>();for(const[k,v]of this.mappings)if(!k.includes('_hash_'))u.set(v.id||k,v);return Array.from(u.values()).slice(-limit).reverse();}
 public getMappingsCount(){let n=0;for(const k of this.mappings.keys())if(!k.includes('_hash_'))n++;return n;}
 public clearMappings(){this.mappings.clear();this.mappingsDirty=true;this.flushMappings();}
 public getConfig(){return{...this.config};}
 public getSafeConfig():Omit<ForwarderConfig,'sessionString'|'botToken'>&{hasSession:boolean;hasBotToken:boolean}{const{sessionString,apiHash,botToken,accounts,...rest}=this.config;return{...rest,accounts:accounts?.map(a=>({id:a.id,name:a.name,username:a.username,phone:a.phone,status:a.status,userProfile:a.userProfile})),apiHash:apiHash?(apiHash.length>8?`${apiHash.slice(0,4)}••••${apiHash.slice(-4)}`:'••••••••'):'',hasSession:Boolean(sessionString&&sessionString.length>5),hasBotToken:Boolean(botToken&&botToken.length>5)};}
 public saveConfig(newConfig:Partial<ForwarderConfig>){this.config={...this.config,...newConfig};try{this.ensureDataDir();const tmp=`${this.configFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(this.config,null,2),'utf8');fs.renameSync(tmp,this.configFile);}catch(err){console.error('[StorageManager] Error writing config:',err);}return this.config;}
 public saveSession(s:string){this.config.sessionString=s;this.saveConfig({sessionString:s});}
 public clearSession(){this.config.sessionString='';this.saveConfig({sessionString:''});}
 public addRule(rule:Omit<ForwardingRule,'id'|'createdAt'>){const r={...rule,id:`rule-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:Date.now()};this.config.rules.push(r);this.saveConfig({rules:this.config.rules});return r;}
 public updateRule(id:string,u:Partial<ForwardingRule>){const i=this.config.rules.findIndex(r=>r.id===id);if(i<0)return null;this.config.rules[i]={...this.config.rules[i],...u};this.saveConfig({rules:this.config.rules});return this.config.rules[i];}
 public deleteRule(id:string){const n=this.config.rules.length;this.config.rules=this.config.rules.filter(r=>r.id!==id);if(this.config.rules.length!==n){this.saveConfig({rules:this.config.rules});return true;}return false;}
}
