import React, { useCallback, useEffect, useState } from 'react';
import { Edit3, FileText, Image, RefreshCw, Send, Trash2, Video, X, Loader2 } from 'lucide-react';

type PendingPost={key:string;sourceId:string;sourceTitle:string;targetId:string;targetTitle:string;messageId:number;text:string;hasMedia:boolean;mediaType:string|null;createdAt:number;mediaUrl?:string|null;mimeType?:string|null;fileName?:string|null;};
const mediaLabel=(type:string|null)=>{const v=(type||'media').toLowerCase();if(v.includes('video'))return'Video';if(v.includes('photo')||v.includes('image'))return'Photo';if(v.includes('document'))return'Document';if(v.includes('audio'))return'Audio';if(v.includes('voice'))return'Voice';if(v.includes('animation')||v.includes('gif'))return'Animation';return'Media';};
const MediaPreview:React.FC<{post:PendingPost}>=({post})=>{if(!post.hasMedia)return null;const label=mediaLabel(post.mediaType);const Icon=label==='Video'?Video:label==='Document'?FileText:Image;return <div className="mt-3 rounded-xl overflow-hidden border border-slate-800 bg-slate-950">{post.mediaUrl&&label==='Video'?<video src={post.mediaUrl} controls preload="metadata" className="w-full max-h-[360px] bg-black"/>:post.mediaUrl&&label==='Photo'?<img src={post.mediaUrl} loading="lazy" alt="Telegram media" className="w-full max-h-[360px] object-contain bg-black"/>:<div className="min-h-[140px] flex items-center justify-center"><div className="text-center text-slate-400"><Icon className="w-9 h-9 mx-auto mb-2 text-cyan-400"/><div className="text-xs font-semibold text-slate-200">{label}</div><div className="text-[10px] mt-1 text-slate-500">Original Telegram media attached to post #{post.messageId}</div></div></div>}</div>};
const Skeleton=()=> <div className="p-4 animate-pulse"><div className="flex flex-col sm:flex-row gap-4"><div className="flex-1 space-y-3"><div className="h-3 w-56 max-w-full rounded bg-slate-800"/><div className="h-24 rounded-xl bg-slate-800"/><div className="h-4 w-3/4 rounded bg-slate-800"/></div><div className="flex sm:flex-col gap-2"><div className="h-9 w-24 rounded-lg bg-slate-800"/><div className="h-9 w-24 rounded-lg bg-slate-800"/></div></div></div>;
export const PendingPosts:React.FC=()=>{
 const[posts,setPosts]=useState<PendingPost[]>([]),[loading,setLoading]=useState(false),[editing,setEditing]=useState<PendingPost|null>(null),[text,setText]=useState(''),[preserveFormatting,setPreserveFormatting]=useState(true),[busyKey,setBusyKey]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/pending',{credentials:'include',cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load pending posts');setPosts(Array.isArray(d.posts)?d.posts:[]);}catch(e:any){setNotice(e.message||'Unable to load pending posts');}finally{setLoading(false);}},[]);
 useEffect(()=>{load();const t=window.setInterval(load,5000);return()=>window.clearInterval(t);},[load]);
 const openEditor=(p:PendingPost)=>{setEditing(p);setText(p.text||'');setPreserveFormatting(true);setNotice(null);};
 const publish=async()=>{if(!editing)return;setBusyKey(editing.key);setNotice(null);try{const r=await fetch(`/api/pending/${encodeURIComponent(editing.key)}/publish`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,preserveFormatting})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Publish failed');setEditing(null);await load();setNotice(`Published Telegram post #${d.sourceMessageId??editing.messageId} to ${editing.targetTitle}.`);}catch(e:any){setNotice(e.message||'Publish failed');}finally{setBusyKey(null);}};
 const publishDirect=async(p:PendingPost)=>{setBusyKey(p.key);setNotice(null);try{const r=await fetch(`/api/pending/${encodeURIComponent(p.key)}/publish`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:p.text})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Publish failed');await load();setNotice(`Published Telegram post #${d.sourceMessageId??p.messageId} to ${p.targetTitle}.`);}catch(e:any){setNotice(e.message||'Publish failed');}finally{setBusyKey(null);}};
 const discard=async(key:string)=>{setBusyKey(key);try{const r=await fetch(`/api/pending/${encodeURIComponent(key)}`,{method:'DELETE',credentials:'include'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Unable to discard post');await load();}catch(e:any){setNotice(e.message||'Unable to discard post');}finally{setBusyKey(null);}};
 return <section className="mb-5 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl overflow-hidden"><div className="px-4 sm:px-5 py-4 flex items-center justify-between gap-3 border-b border-slate-800"><div className="min-w-0"><h2 className="text-sm font-bold text-white flex items-center gap-2"><Edit3 className="w-4 h-4 text-cyan-400"/>Pending Posts</h2><p className="text-[11px] text-slate-500 mt-1">Real source messages waiting for review, editing, approval, and Telegram delivery.</p></div><button onClick={load} disabled={loading} className="p-2 rounded-lg bg-slate-800 text-slate-300 hover:text-white disabled:opacity-50 shrink-0" title="Refresh pending posts"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>
 {notice&&<div className="px-4 sm:px-5 py-3 text-xs text-cyan-300 bg-cyan-950/30 border-b border-cyan-900/50 break-words">{notice}</div>}
 {loading?<div className="divide-y divide-slate-800"><Skeleton/><Skeleton/></div>:posts.length===0?<div className="px-5 py-8 text-center text-xs text-slate-500">No source posts are waiting for review.</div>:<div className="divide-y divide-slate-800">{posts.map(p=><article key={p.key} className="p-4"><div className="flex flex-col lg:flex-row gap-4 items-stretch lg:items-start"><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 text-[10px] text-slate-500 mb-2"><span className="px-2 py-1 rounded-md bg-slate-800 text-slate-300">POST #{p.messageId}</span><span className="px-2 py-1 rounded-md bg-slate-800">{new Date(p.createdAt).toLocaleString()}</span><span className="px-2 py-1 rounded-md bg-cyan-950/40 text-cyan-300 break-all">SOURCE: {p.sourceTitle||p.sourceId}</span><span className="px-2 py-1 rounded-md bg-emerald-950/40 text-emerald-300 break-all">DESTINATION: {p.targetTitle||p.targetId}</span></div><div className="rounded-xl bg-slate-950 border border-slate-800 p-3 sm:p-4"><p className="text-sm text-slate-200 whitespace-pre-wrap break-words">{p.text||'(media-only post)'}</p><MediaPreview post={p}/></div></div><div className="grid grid-cols-3 lg:flex lg:flex-col gap-2 shrink-0"><button onClick={()=>openEditor(p)} className="px-2 sm:px-3 py-2 rounded-lg bg-cyan-600/20 border border-cyan-700 text-cyan-300 text-[11px] sm:text-xs font-semibold flex items-center justify-center gap-1.5"><Edit3 className="w-3.5 h-3.5"/>Edit</button><button onClick={()=>publishDirect(p)} disabled={busyKey===p.key} className="px-2 sm:px-3 py-2 rounded-lg bg-emerald-600/20 border border-emerald-700 text-emerald-300 text-[11px] sm:text-xs font-semibold flex items-center justify-center gap-1.5 disabled:opacity-50"><Send className="w-3.5 h-3.5"/>{busyKey===p.key?'Sending…':'Publish'}</button><button onClick={()=>discard(p.key)} disabled={busyKey===p.key} className="px-2 sm:px-3 py-2 rounded-lg bg-rose-950/40 border border-rose-900 text-rose-300 text-[11px] sm:text-xs font-semibold flex items-center justify-center gap-1.5 disabled:opacity-50"><Trash2 className="w-3.5 h-3.5"/>Delete</button></div></div></article>)}</div>}
 {editing&&<div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4"><div className="w-full max-w-2xl rounded-2xl bg-slate-900 border border-slate-700 shadow-2xl p-4 sm:p-5 space-y-4 max-h-[94vh] overflow-y-auto"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><h3 className="text-base font-bold text-white">Edit Source Post #{editing.messageId}</h3><p className="text-xs text-slate-400 mt-1 truncate">{editing.sourceTitle} → {editing.targetTitle}</p></div><button onClick={()=>setEditing(null)} className="p-2 text-slate-400 hover:text-white shrink-0"><X className="w-4 h-4"/></button></div>{editing.hasMedia&&<MediaPreview post={editing}/>}<div><label className="block text-[10px] uppercase tracking-wide text-slate-500 mb-2">Editable text / caption</label><textarea value={text} onChange={e=>setText(e.target.value)} rows={9} className="w-full px-3 py-3 bg-slate-950 border border-slate-800 rounded-xl text-sm text-white focus:outline-none focus:border-cyan-500" placeholder="Edit the caption/text before publishing…"/></div><label className="flex items-center gap-3 rounded-xl bg-slate-950 border border-slate-800 p-3 cursor-pointer"><input type="checkbox" checked={preserveFormatting} onChange={e=>setPreserveFormatting(e.target.checked)} className="accent-cyan-500"/><span><span className="block text-xs font-semibold text-slate-200">Preserve formatting</span><span className="block text-[10px] text-slate-500 mt-0.5">Keep Telegram formatting where supported when the edited caption is published.</span></span></label><div className="flex flex-col-reverse sm:flex-row justify-end gap-2"><button onClick={()=>setEditing(null)} className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs font-semibold">Cancel</button><button onClick={publish} disabled={busyKey===editing.key} className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white text-xs font-bold flex items-center justify-center gap-2"><Send className="w-3.5 h-3.5"/>{busyKey===editing.key?'Publishing…':'Forward / Publish'}</button></div></div></div>}
 </section>;
};